### ISSUE TITLE
Add metafiles to .gitignore

### ISSUE THREAD

**Issue by netcodedev** [bitbitedev/OpenLogLib#19]
Files that should not be tracked:
- [x] .classpath
- [x] .gradle/
- [x] .project
- [x] *.prefs

**Comment by ThatsNasu** [comment]
They are not tracked. But i added the gitignore to the gitignore, so these files are depending on user settings after cloning the repository. If they were tracked, they would be in the source.

**Comment by netcodedev** [comment]
The gitignore should not be excluded. If someone wants to contribute to the project and forks it pull requests might include unwanted files. 
And the files mentioned are indeed being tracked, thats why i requested to add them to the `.gitignore`. You might have to delete them first to remove them from the repo and future commits
