### ISSUE TITLE
Separate Date and Time in LogProperties

### ISSUE THREAD

**Issue by netcodedev** [bitbitedev/OpenLogLib#23]
To increase flexibility Date and time should be addressable separately so that more stylings are possible.
For example different colors within the date time string are not possible at the moment. If you want the date/time to be shown something like this:
`[2022-05-13][11:57:43]` while all brackets should have the same color while the date text should have a different color. This is not possible at the moment

**Comment by ThatsNasu** [comment]
you can always extend the presets and add your own to your delight

**Comment by netcodedev** [comment]
I know but i think those are important enough to be available by default

**Comment by netcodedev** [comment]
EDIT: The presets dont support dynamic content. The time changes every second but there is no way to tell the Log to render out the current time. You can just set a static string.

**Comment by ThatsNasu** [comment]
the log always uses the current time to log the messages (Log.replaceDynamicElements())

**Comment by netcodedev** [comment]
yes but only for the predefined time template string. currently there is no way to add a second time string
