### ISSUE TITLE
Add further formatting options

### ISSUE THREAD

**Issue by netcodedev** [bitbitedev/OpenLogLib#24]
Additionally to the colorization and text formatting there should be the ability to add further preprocessing like uppercasing/lowercasing or anything else that involves String transformation. Optimaly the API should allow to pass multiple functions that take in a string and return a string to be set.
The api could be something like this: 
```java
new FormatBuilder().setAnsi(ansi).addPreFormatting(String::toLowerCase, String::toString).get()
```
tho this example would make too much of a sense but i think you get the point

**Comment by ThatsNasu** [comment]
closed, not part of this repository
